### ISSUE TITLE
1.2.0 - no way to specify authentication method

### ISSUE THREAD

**Issue by zgoda** [fauna/fauna-shell#333]
With 1.1.2 I could select either credentials or secret authentication upon 1st `cloud-login` invocation, now 1.2.0 allows only credentials authentication. The issue is, I'm logging in to dashboard with Github auth and I don't have password.

**Comment by ptpaterson** [comment]
Hi @zgoda You can create a password for your email by going through the _Forgot password_ workflow

https://dashboard.fauna.com/forgot-password

Additionally, if you have a database secret, you can create new endpoints for databases using `fauna endpoint add` instead of `fauna cloud-login`. Then you do not need to authenticate at all.

**Comment by echo-bravo-yahoo** [comment]
Closing due to no reply. Please re-open if you continue to have issues with auth.
