### ISSUE TITLE
cloud-login with GitHub Auth

### ISSUE THREAD

**Issue by abegehr** [fauna/fauna-shell#95]
The link at https://github.com/fauna/fauna-shell/blob/master/README.md#usage does not work.

This is the link: https://docs.fauna.com/fauna/current/start/cloud-github.html

**Comment by jfrancos** [comment]
I'm also trying to figure out how to log into fauna-shell if my provider is Netlify.  The readme here says
> If you would like to use 3rd party identity providers like Github or Netlify, please refer to [this guide](https://docs.fauna.com/fauna/current/start/cloud-github.html).

That's the broken link.  Neither `fauna cloud-login --help` nor `fauna --help` seem to help here.
I wouldn't mind solving this problem by converting my account to authenticate directly with FaunaDB instead of through Netlify, but I'm not sure how to do that either.
